# .readthedocs.yaml
# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      path: .  # installs sfinance using pyproject.toml

sphinx:
  configuration: docs/conf.py
